language: python
python:
  - "2.7"
  - "3.4"


cache:
  directories:
    - $HOME/.cache/pip
  pip: true

sudo: false

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

# command to install dependencies
addons:
  apt:
    packages:
    - libatlas-dev
    - liblapack-dev
    - libatlas-base-dev
    - gfortran

install:
  - pip install pip --upgrade
  - pip install numpy
  - pip install nose
  - pip install coverage
  - python setup.py install

# command to run tests, e.g. python setup.py test
script:
  - nosetests --with-coverage

after_success::
  - coveralls
